### ISSUE TITLE
status.figuren.theater

### ISSUE THREAD

**Issue by carstingaxion** [figuren-theater/status.figuren.theater#1]
```[tasklist]
### Tasks
- [ ] https://github.com/figuren-theater/status.figuren.theater/issues/2
- [ ] https://github.com/figuren-theater/status.figuren.theater/issues/3
- [ ] https://github.com/figuren-theater/status.figuren.theater/issues/4
```
